Feat/payment methods
PaddleHQ/paddle-python-sdk pull request #67
Opened 2024-11-12 22:16 UTC by davidgrayston-paddle

### Added

- Support for saved payment methods, see [related changelog](https://developer.paddle.com/changelog/2024/saved-payment-methods?utm_source=dx&utm_medium=paddle-python-sdk)
  - `Client.payment_methods.list`
  - `Client.payment_methods.get`
  - `Client.payment_methods.delete`
  - `Client.customers.create_auth_token`

2024-11-12 22:25 UTC, davidgrayston-paddle commented on paddle_billing/Notifications/Entities/Entity.py
> +        return event_entity.lower().title().replace("_", "")
This replacement is needed to convert `payment_method` → `PaymentMethod`

2024-11-12 22:25 UTC, davidgrayston-paddle commented on paddle_billing/Notifications/Entities/PaymentMethodDeleted.py
> +    deletion_reason: SavedPaymentMethodDeletionReason
`PaymentMethodDeleted` entity has additional `deletion_reason` property

2024-11-14 09:27 UTC, vifer submitted a review, later dismissed

2024-11-14 14:14 UTC, vifer requested changes

2024-11-14 14:14 UTC, vifer commented on paddle_billing/Entities/Shared/PaymentMethodType.py
> +    PayPal: "PaymentMethodType" = "paypal"
@davidgrayston-paddle this might be a breaking change, let's keep what we originally had

2024-11-14 14:56 UTC, vifer approved these changes

2024-11-14 15:15 UTC, merged